### ISSUE TITLE
Epic-Fake views

### ISSUE THREAD

**Issue by Kingbrianss** [Kingbrianss/KING#1]
descripcion. realizar el mapa de navegación con fake views del proyecto BarbSport

![Captura de pantalla 2024-03-07 164129](https://github.com/Kingbrianss/Procesos/assets/160792589/f956d7fd-101e-4d11-ae4d-76bece5cc7ec)

Tasks:

- [ ] fake landing_page
- [ ] fake login 
- [ ] fake sigup
- [ ] fake forgot_password
- [ ] fake splash_screen 
- [ ] fake home 
- [ ] fake logout
